---
title: "hw05"
format: html
editor: visual
---

# Analyzing Factors Contributing to Loss of Bee Colonies in Arizona

## Code

```{r}

# Load packages

if (!require(pacman))
  install.packages("pacman")

pacman::p_load(tidymodels,
               dplyr,
               tidyverse,
               ranger,
               randomForest,
               glmnet,
               here,
               formattable,
               dlookr,
               yardstick,
               gridExtra)
```

```{r}

# Import two correlated datasets, "colony" and "stressor": 

# Read colony data (dataset is from 2015 - 2021)
colony <- read_csv(here('./data/colony.csv'))
arizona_colony <- filter(colony, state %in% "Arizona")
arizona_colony

# Read stressor data
stressor <- read_csv(here('./data/stressor.csv'))
arizona_stressor <- filter(stressor, state %in% "Arizona")
arizona_stressor
```

```{r}

# Analyze "arizona_colony" data: 

arizona_colony |> summary()

# Check for missing values: 

na_values_arizona_colony <- colSums(is.na(arizona_colony))
na_values_arizona_colony

# Analyze and inspect the rows missing values: 

missing_rows_arizona_colony <- arizona_colony %>%
  filter(!complete.cases(.))
missing_rows_arizona_colony

# Remove "colony_reno_pct" (impute):

arizona_colony %>%
    select(-colony_reno_pct) %>%
    filter(!complete.cases(.))
arizona_colony

# Don't impute April-June 2019, and remove row, as this is only row with null values and entire row of data wasn't collected: 

arizona_colony %>% na.omit()
```

```{r}

# Filter stressor data: 

arizona_data$stressor <- as.factor(arizona_data$stressor)

arizona_stressor_counts <- table(arizona_data$stressor)

arizona_stressor <- table(arizona_data$stressor)

arizona_stressor_rank <- rank(-arizona_stressor_counts, ties.method = "min")

arizona_stressor_summary <- data.frame(
  Stressor = names(arizona_stressor_counts),
  Count = arizona_stressor_counts,
  Rank = arizona_stressor_rank)

arizona_stressor
```

## Part I of II: Colony Lost Analysis

This dataset views the trend of bee colonies lost in Arizona over a six-year period (2015-2021).

```{r}

# Analyze Colony Lost - Max & Min 

stressor_counts <- table(stressor$stressor)
stressor_counts

max_colony_stressor <- max(stressor$stressor)
min_colony_stressor <- min(stressor$stressor)
max_colony
min_age
```

## Part II of II: Stressors Killing Bee Colonies

```{r}

# Need to classify "Stressors" as factors instead of characters:



my_data$Name <- as.factor(my_data$Name)
```
